apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:712044128773:certificate/933f1331-66ff-492f-80d1-2f4f9a62c2a0
    alb.ingress.kubernetes.io/group.name: shopcloud-public
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "15"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/certificate-arn":"arn:aws:acm:eu-central-1:712044128773:certificate/933f1331-66ff-492f-80d1-2f4f9a62c2a0","alb.ingress.kubernetes.io/group.name":"shopcloud-public","alb.ingress.kubernetes.io/healthcheck-interval-seconds":"15","alb.ingress.kubernetes.io/healthcheck-path":"/","alb.ingress.kubernetes.io/listen-ports":"[{\"HTTP\":80},{\"HTTPS\":443}]","alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-type":"ip","kubernetes.io/ingress.class":"alb"},"name":"public-ingress","namespace":"app"},"spec":{"ingressClassName":"alb","rules":[{"host":"www.welovedassouki.store","http":{"paths":[{"backend":{"service":{"name":"auth","port":{"number":80}}},"path":"/auth","pathType":"Prefix"},{"backend":{"service":{"name":"api-gateway","port":{"number":80}}},"path":"/api","pathType":"Prefix"},{"backend":{"service":{"name":"customer-web","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    kubernetes.io/ingress.class: alb
  creationTimestamp: "2026-04-30T23:46:53Z"
  finalizers:
  - group.ingress.k8s.aws/shopcloud-public
  generation: 3
  name: public-ingress
  namespace: app
  resourceVersion: "357766"
  uid: bd0705b2-7c1e-4a04-834f-f28bbe4244d0
spec:
  ingressClassName: alb
  rules:
  - host: www.welovedassouki.store
    http:
      paths:
      - backend:
          service:
            name: auth
            port:
              number: 80
        path: /auth
        pathType: Prefix
      - backend:
          service:
            name: api-gateway
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: customer-web
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer:
    ingress:
    - hostname: k8s-shopcloudpublic-3976a6d8dc-1488320077.eu-central-1.elb.amazonaws.com
