name: CI Auth

on:
  push:
    paths:
      - "shopcloud/services/auth/**"
      - "shopcloud/libs/**"
      - ".github/workflows/ci-auth.yml"
      - ".github/workflows/reusable-build-deploy.yml"
  pull_request:
    paths:
      - "shopcloud/services/auth/**"
      - "shopcloud/libs/**"
      - ".github/workflows/ci-auth.yml"
      - ".github/workflows/reusable-build-deploy.yml"

permissions:
  contents: read
  id-token: write

jobs:
  auth:
    uses: ./.github/workflows/reusable-build-deploy.yml
    with:
      service: auth
      service_path: shopcloud/services/auth
    secrets:
      aws_role_arn: ${{ secrets.AWS_OIDC_ROLE_ARN_DEV }}
