name: CI Catalog

on:
  push:
    paths:
      - "shopcloud/services/catalog/**"
      - "shopcloud/libs/**"
      - ".github/workflows/ci-catalog.yml"
      - ".github/workflows/reusable-build-deploy.yml"
  pull_request:
    paths:
      - "shopcloud/services/catalog/**"
      - "shopcloud/libs/**"
      - ".github/workflows/ci-catalog.yml"
      - ".github/workflows/reusable-build-deploy.yml"

permissions:
  contents: read
  id-token: write

jobs:
  catalog:
    uses: ./.github/workflows/reusable-build-deploy.yml
    with:
      service: catalog
      service_path: shopcloud/services/catalog
    secrets:
      aws_role_arn: ${{ secrets.AWS_OIDC_ROLE_ARN_DEV }}
