name: Terraform Secrets Module CI

on:
  pull_request:
    branches: [main, dev]
    paths:
      - "shopcloud/infra/envs/dev/modules/secrets/**"
      - "shopcloud/infra/envs/prod/modules/secrets/**"
      - ".github/workflows/tf-secrets-ci.yml"
      - ".github/workflows/_reusable-tf-module-ci.yml"
  push:
    branches: [main, dev]
    paths:
      - "shopcloud/infra/envs/dev/modules/secrets/**"
      - "shopcloud/infra/envs/prod/modules/secrets/**"
      - ".github/workflows/tf-secrets-ci.yml"
      - ".github/workflows/_reusable-tf-module-ci.yml"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: tf-secrets-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate_dev:
    uses: ./.github/workflows/_reusable-tf-module-ci.yml
    with:
      module_path: shopcloud/infra/envs/dev/modules/secrets
      module_name: secrets (dev)
  validate_prod:
    uses: ./.github/workflows/_reusable-tf-module-ci.yml
    with:
      module_path: shopcloud/infra/envs/prod/modules/secrets
      module_name: secrets (prod)


